// <auto-generated />
using AsyncReqReplyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsyncReqReplyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230224095546_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("AsyncReqReplyAPI.Models.ListingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("EstimatedCompletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("EstimatedCompletionTime");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT")
                        .HasColumnName("RequestBody");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RequestId");

                    b.Property<string>("RequestStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("RequestStatus");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ListingRequest", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
